<html>
	<head>
		
	</head>
	<body>
		<script type="text/javascript">
				
		//获取Location对象的search属性值
		//如：?id=122844&jituanyw=1195
		var searchStr = location.search;
		
		//重定向 url
		var links = "../newsDetail.html" + searchStr;
		window.location.href=links;
		
		</script>
 
	</body>
</html>
